Disambiguate unarchive actions by output name
Summary:
This diff makes it possible to perform multiple `unarchive` within the same target, for example for unarchiving multiple sub_targets.

Previously, it would have failed because each `unarchive` would try to declare the same set of output names and action names.

```lang=text,counterexample
  * stage0/defs.bzl:132, in _stage0_extract_impl
      contents, _ = unarchive(
  * prelude/http_archive/unarchive.bzl:169, in unarchive
      script, _ = ctx.actions.write(

error: Multiple artifacts and/or metadata files are declared at the same output location `unpack.sh` declared at `prelude/http_archive/unarchive.bzl:169:17-178:6`.
   --> prelude/http_archive/unarchive.bzl:169:17
    |
169 |       script, _ = ctx.actions.write(
    |  _________________^
170 | |         "unpack.{}".format(ext),
171 | |         [
172 | |             cmd_args(script_output, format = mkdir),
173 | |             cmd_args(script_output, format = "cd {}"),
174 | |             cmd_args([unarchive_cmd] + exclude_flags, delimiter = " ", relative_to = script_output),
175 | |         ],
176 | |         is_executable = True,
177 | |         allow_args = True,
178 | |     )
    | |_____^
    |
```

Reviewed By: JakobDegen

Differential Revision: D74022538

fbshipit-source-id: f11678b70f642208bd15e0859edf59442ff6441b
Change-Id: Ib9c064acf6939be0caa366a08f683de03fa24d8f