Allow strings with resolved parameter macros
The compiler_flags attribute is declared as a list of `attr.arg` which means
the items of the list of `ctx.attrs.compiler_flags` are not simply strings,
but of type `ResolvedStringWithMacros`.

This avoids a type mismatch like:

```
error: Value `["-Wno-x-partial"]` of type `list` does not match the type annotation `list[str]` for argument `compiler_flags`
```

Change-Id: I0f0cd030bb2c0b0c12a53b0cdaa4b2bfde9148b6